apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-app
spec:
  selector:
    matchLabels:
      app: patient-service-app
  template:
    metadata:
      labels:
        app: patient-service-app
    spec:
      containers:
        - name: patient-service-app
          image: IMAGE_URL/patientservice
          imagePullPolicy: Always
          ports:
            - containerPort: 8089
          env:

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-cm
                  key: hostname
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi


---

apiVersion: v1
kind: Service
metadata:
  name: patient-service-svc
spec:
  type: LoadBalancer
  selector:
    app: patient-service-app
  ports:
    - port: 80
      targetPort: 8089